# Generated by Django 2.0.4 on 2018-05-16 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180516_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, default=' ', max_length=140, null=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('weekday', models.IntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookform',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='bookform',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookForm',
        ),
    ]
