# Generated by Django 2.0.4 on 2018-05-17 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_appointments_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='groomingoptions',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
